### ISSUE TITLE
Deprecate old package at npm

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/frost-client#72]
We moved the package from https://www.npmjs.com/package/@poetapp/frost-client to https://www.npmjs.com/package/@po.et/frost-client a while back but the old one's still available and people keep using it.

The best way to address this is probably to change the name of the project in the package.json back to `@poetapp/frost-client` temporarily, remove all code, update the readme, bump up major version, publish and not commit any of these changes to the GH repo.

Readme should have a deprecation notice and link to new NPM repo.

This is very low priority.

**Comment by wzalazar** [comment]
@lautarodragan is enough for you this messages?

<img width="762" alt="screen shot 2018-11-08 at 14 44 58" src="https://user-images.githubusercontent.com/5795257/48217131-58740280-e365-11e8-9008-abd20510ea5c.png">

![screen shot 2018-11-08 at 14 47 24](https://user-images.githubusercontent.com/5795257/48217121-514cf480-e365-11e8-9a05-5f02447fe9db.png)

**Comment by lautarodragan** [comment]
Yep, great!
